# Generated by Django 5.1.2 on 2024-10-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('eco_friendly_certifications', models.CharField(max_length=255)),
                ('product_image_url', models.URLField(max_length=500)),
            ],
        ),
    ]
