# Generated by Django 5.1.2 on 2024-11-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_webapp', '0004_remove_order_buyer_id_remove_cart_buyer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
