# Generated by Django 5.1.2 on 2024-11-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_webapp', '0005_product_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_url',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
