# Generated by Django 5.1.2 on 2024-11-01 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_webapp', '0006_alter_product_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image_url',
            new_name='product_image',
        ),
    ]
