# Generated by Django 5.1.2 on 2024-11-02 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_webapp', '0010_alter_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
