# Generated by Django 5.1.2 on 2024-11-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_webapp', '0012_ordereditems_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='quantity',
        ),
    ]
