# Generated by Django 5.1.2 on 2024-11-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_webapp', '0013_remove_ordereditems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='product_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
